const vacantes = [
  {
    logo: "/iconofarmworker.png",
    empresa: "Delta Dairy LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Baskin, Louisiana",
    descripcion: "Operación de equipos agrícolas, mantenimiento de tierras y estanques, asistencia con ganado y tareas de saneamiento.",
    salario: "$14.83 por hora",
    posiciones: ["4"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25174-121326",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Walter P Rawl & Sons Inc",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Pelion, Carolina del Sur",
    descripcion: "Cosecha y empaque de vegetales de hoja, mantenimiento de campos e irrigación.",
    salario: "$16.08 por hora",
    posiciones: ["396"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25175-123468",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Group Orchards, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Gardners, Pensilvania",
    descripcion: "Cosecha de manzanas, clasificación y empaque según estándares de calidad.",
    salario: "$17.96 por hora (garantizado); $25 por caja de manzanas",
    posiciones: ["No especificado"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25149-028998",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Ourso Farms, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "White Castle, Luisiana",
    descripcion: "Cultivo y cosecha de caña de azúcar, soya y trigo; mantenimiento de equipos y estructuras agrícolas.",
    salario: "$14.83 por hora",
    posiciones: ["No especificado"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25140-995597",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Peri & Sons Farms, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Yerington, Nevada",
    descripcion: "Cosecha de vegetales, operación de equipos agrícolas y mantenimiento general de campos.",
    salario: "$14.68 por hora",
    posiciones: ["No especificado"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25092-825078",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Barlow Farms LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Oscar, Luisiana",
    descripcion: "Operación de maquinaria agrícola, irrigación y mantenimiento de cultivos de soya, maíz y caña de azúcar.",
    salario: "$14.83 por hora",
    posiciones: ["11"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25147-021312",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Lewis M Bailey IV Farms Inc",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Bruce, Misisipi",
    descripcion: "Plantación, cultivo y cosecha de batatas; carga y descarga de productos.",
    salario: "$14.83 por hora (garantizado); $0.50 por cubeta de 3 galones",
    posiciones: ["No especificado"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25169-107889",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "T & T Family Farms",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Plaza, Dakota del Norte",
    descripcion: "Cosecha de granos, siembra de cultivos, mezcla de químicos y operación de equipos agrícolas.",
    salario: "$18.32 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-23352-575391",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Aloun Farm, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Kaumakani, Hawái",
    descripcion: "Plantación, cultivo y cosecha de diversos cultivos; operación de maquinaria agrícola.",
    salario: "$20.08 por hora",
    posiciones: ["38"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25122-932464",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Ochsner Partnership",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Hosmer, Dakota del Sur",
    descripcion: "Alimentación y cuidado de ganado, mantenimiento de registros y asistencia en partos.",
    salario: "$19.21 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25107-875773",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Noble House Snake River LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Jackson, WY",
    descripcion: "",
    salario: "$19.00 por hora",
    horario: "35 horas semanales; turnos variables entre las 7:00 a.m. y las 10:00 p.m.",
    posiciones: ["Cocinero/a"],
    fechas: "Inicio: 1 de mayo de 2025 – Fin: 31 de octubre de 2025",
    idioma: "Inglés básico",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-25041-681584",
    boton: "Postular ahora",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Holiday Inn Club Vacations Incorporated",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Stateline, NV",
    descripcion: "",
    salario: "$17.00 por hora",
    horario: "35 horas semanales; turnos rotativos entre las 7:00 a.m. y las 11:00 p.m.",
    posiciones: ["Recepcionista de hotel"],
    fechas: "Inicio: 1 de noviembre de 2023 – Fin: 31 de agosto de 2024",
    idioma: "Inglés básico",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-23224-260230",
    boton: "Postular ahora",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Igloo Products Corp.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Katy, TX",
    descripcion: "",
    salario: "$16.53 por hora",
    horario: "48 horas semanales; turnos rotativos de 12 horas",
    posiciones: ["Ayudante de producción"],
    fechas: "Inicio: 1 de octubre de 2024 – Fin: 30 de junio de 2025",
    idioma: "No se requiere",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-171437",
    boton: "Postular ahora",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Jonathan's Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Ogunquit, ME",
    descripcion: "",
    salario: "$18.28 por hora",
    horario: "35 horas semanales, turnos rotativos entre las 10:00 a.m. y las 11:00 p.m.",
    posiciones: ["Cocinero/a"],
    fechas: "1 de abril de 2024 – 30 de noviembre de 2024",
    alojamiento: "Opcional, $275 quincenales",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24122-163963",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Broken Sound Club, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Boca Raton, FL",
    descripcion: "",
    salario: "$17.00 por hora",
    horario: "40 horas semanales, turnos variables entre las 6:00 a.m. y las 11:00 p.m.",
    posiciones: ["Mesero/a"],
    fechas: "1 de octubre de 2024 – 31 de mayo de 2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24139-180399",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Igloo Products Corp.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Katy, TX",
    descripcion: "",
    salario: "$16.53 por hora",
    horario: "48 horas semanales, turnos rotativos de 12 horas",
    posiciones: ["Ayudante de Producción"],
    fechas: "1 de octubre de 2024 – 30 de junio de 2025",
    idioma: "No se requiere",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-171437",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Boca West Country Club, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Boca Raton, FL",
    descripcion: "",
    salario: "No especificado",
    horario: "40 horas semanales, turnos variables",
    posiciones: ["Salvavidas"],
    fechas: "No especificadas",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24139-180400",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Ocean Gold Seafoods, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Westport, WA",
    descripcion: "",
    salario: "$16.70 por hora",
    horario: "35 horas semanales, turnos de 12 horas",
    posiciones: ["Procesador/a de Mariscos"],
    fechas: "15 de mayo de 2025 – 31 de octubre de 2025",
    alojamiento: "Opcional, $100 semanales",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24141-182017",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Chez Francois Seafood",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Lafayette, LA",
    descripcion: "",
    salario: "$12.68 por hora",
    horario: "35 horas semanales, de 6:00 a.m. a 4:00 p.m.",
    posiciones: ["Procesador/a de Mariscos"],
    fechas: "1 de diciembre de 2024 – 30 de septiembre de 2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24189-175017",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "E.C. Phillips & Son, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Ketchikan, AK",
    descripcion: "",
    salario: "$17.15 por hora",
    horario: "40 horas semanales, turnos variables",
    posiciones: ["Procesador/a de Mariscos"],
    fechas: "1 de abril de 2024 – 30 de noviembre de 2024",
    alojamiento: "Opcional, $8 diarios",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24062-785524",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Empresa Ejemplo 20",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Ciudad Genérica, EE.UU.",
    descripcion: "",
    salario: "$17.00 por hora",
    horario: "40 horas semanales, turnos rotativos",
    posiciones: ["Asistente general"],
    fechas: "Inicio: 1 de mayo de 2025 – Fin: 31 de octubre de 2025",
    idioma: "Español / Inglés básico",
    link: "https://seasonaljobs.dol.gov/jobs",
    boton: "Postular ahora",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "SUNRISE BUILDERS LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Wailuku, HI",
    descripcion: "",
    salario: "$28.85 por hora",
    horario: "No especificado",
    posiciones: ["Obrero de Construcción"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175430",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "FDR Contractors Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Naples, FL",
    descripcion: "",
    salario: "$17.38 por hora",
    horario: "No especificado",
    posiciones: ["Ayudante de Albañilería"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-174315",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "R. J. Corman Railroad Services, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Nicholasville, KY",
    descripcion: "",
    salario: "$20.00 por hora",
    horario: "No especificado",
    posiciones: ["Obrero de Ferrocarril"],
    fechas: "15/03/2025 – 15/11/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175288",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "MCI Construction Group Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Fort Lauderdale, FL",
    descripcion: "",
    salario: "$18.00 por hora",
    horario: "No especificado",
    posiciones: ["Asistente de Obra"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-172920",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "V-Construction Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Denver, CO",
    descripcion: "",
    salario: "$24.34 por hora",
    horario: "No especificado",
    posiciones: ["Especialista en Demoliciones"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175035",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Abhe & Svoboda, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Lakeville, MN",
    descripcion: "",
    salario: "$35.85 por hora",
    horario: "No especificado",
    posiciones: ["Técnico de Reparaciones Estructurales"],
    fechas: "01/04/2025 – 15/12/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175200",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Western Steel Erectors Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Hamilton, MT",
    descripcion: "",
    salario: "$24.00 por hora",
    horario: "No especificado",
    posiciones: ["Montador de Acero"],
    fechas: "01/04/2025 – 01/12/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175160",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Luis Lerebours LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "North Miami Beach, FL",
    descripcion: "",
    salario: "$18.50 por hora",
    horario: "No especificado",
    posiciones: ["Ayudante de Instalaciones"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-174200",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Robinson Landscape Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Morrisville, PA",
    descripcion: "",
    salario: "$22.75 por hora",
    horario: "No especificado",
    posiciones: ["Trabajador General de Construcción"],
    fechas: "01/04/2025 – 30/11/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175038",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "CCI Industrial Services LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Anchorage, AK",
    descripcion: "",
    salario: "$27.00 por hora",
    horario: "No especificado",
    posiciones: ["Ayudante de Carpintería"],
    fechas: "01/04/2025 – 30/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-174809",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Inland Construction & Development Co.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Spokane, WA",
    descripcion: "",
    salario: "$28.00 por hora",
    horario: "No especificado",
    posiciones: ["Albañil Asistente"],
    fechas: "15/04/2025 – 15/11/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175234",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Sunburst Landscaping Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Phoenix, AZ",
    descripcion: "",
    salario: "$18.00 por hora",
    horario: "No especificado",
    posiciones: ["Ayudante de Jardinería Hardscape"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175255",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Field Source Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Miami, FL",
    descripcion: "",
    salario: "$18.45 por hora",
    horario: "No especificado",
    posiciones: ["Técnico de Mantenimiento Exterior"],
    fechas: "01/10/2024 – 30/06/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175260",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Hardscape Design Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Indianapolis, IN",
    descripcion: "",
    salario: "$22.00 por hora",
    horario: "No especificado",
    posiciones: ["Oficial de Obra General"],
    fechas: "01/04/2025 – 30/11/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24185-175262",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Auvil Fruit Company, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Orondo, WA",
    descripcion: "",
    salario: "$18.35 por hora",
    horario: "No especificado",
    posiciones: ["Trabajador de Huerto Frutal"],
    fechas: "01/04/2025 – 15/11/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24135-975123",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Stemilt AG Services LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Wenatchee, WA",
    descripcion: "",
    salario: "$17.97 por hora",
    horario: "No especificado",
    posiciones: ["Cosechador de Manzanas"],
    fechas: "15/06/2025 – 31/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24155-975789",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Blue Bird, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Manson, WA",
    descripcion: "",
    salario: "$18.34 por hora",
    horario: "No especificado",
    posiciones: ["Trabajador Agrícola en Perales"],
    fechas: "01/05/2025 – 30/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24150-975543",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Cowiche Growers, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Cowiche, WA",
    descripcion: "",
    salario: "$18.30 por hora",
    horario: "No especificado",
    posiciones: ["Podador de Árboles Frutales"],
    fechas: "15/03/2025 – 30/09/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24144-975312",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Zirkle Fruit Company",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Selah, WA",
    descripcion: "",
    salario: "$18.33 por hora",
    horario: "No especificado",
    posiciones: ["Recolector de Cereza"],
    fechas: "01/06/2025 – 30/08/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24155-975600",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Gilbert Orchards, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Yakima, WA",
    descripcion: "",
    salario: "$18.31 por hora",
    horario: "No especificado",
    posiciones: ["Trabajador de Huerto Orgánico"],
    fechas: "01/04/2025 – 30/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24145-975432",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Broetje Orchards LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Prescott, WA",
    descripcion: "",
    salario: "$18.20 por hora",
    horario: "No especificado",
    posiciones: ["Mantenimiento de Árboles Frutales"],
    fechas: "01/05/2025 – 15/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24154-975526",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Borton & Sons, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Yakima, WA",
    descripcion: "",
    salario: "$18.50 por hora",
    horario: "No especificado",
    posiciones: ["Ayudante de Cosecha de Frutas"],
    fechas: "01/05/2025 – 31/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24155-975602",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Mercer Ranches, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Prosser, WA",
    descripcion: "",
    salario: "$18.35 por hora",
    horario: "No especificado",
    posiciones: ["Trabajador de Viñedo"],
    fechas: "15/04/2025 – 15/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24154-975528",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Hansen Fruit Company LP",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Yakima, WA",
    descripcion: "",
    salario: "$18.25 por hora",
    horario: "No especificado",
    posiciones: ["Recolector de Frutas Mixtas"],
    fechas: "01/05/2025 – 30/10/2025",
    idioma: "No especificado",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24154-975540",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "DJ Stephens Farms LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Wingo, Kentucky",
    descripcion: "Operación de tractores y equipos agrícolas para labranza, siembra, cultivo y cosecha de cultivos; mantenimiento y reparación de maquinaria agrícola.",
    salario: "$15.87 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25169-108518",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "TJHG, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "South Fulton, Tennessee",
    descripcion: "Manejo de maquinaria agrícola para preparación de terrenos, siembra y cosecha; mantenimiento de equipos y estructuras agrícolas.",
    salario: "$15.87 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25175-124890",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "GDM Seeds, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Jonesboro, Arkansas",
    descripcion: "Operación de maquinaria agrícola para labranza, siembra y cosecha; mantenimiento de equipos y sistemas de riego; inspección y cuidado de cultivos.",
    salario: "$17.15 por hora",
    posiciones: ["38"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25160-070170",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Jelinek Custom Cleaning, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Alliance, Nebraska",
    descripcion: "Carga y descarga de cultivos; mezcla y aplicación de fertilizantes y pesticidas; operación y mantenimiento de maquinaria agrícola.",
    salario: "$19.21 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25169-107965",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Datthyn Fruit Farm, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Sodus, Nueva York",
    descripcion: "Poda de árboles, cosecha de manzanas, mantenimiento de huertos y reparación de contenedores; transporte de trabajadores y suministros en la finca.",
    salario: "$18.83 por hora",
    posiciones: ["32"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25175-123326",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Brumfield Angus Farms, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Wilsall, Montana",
    descripcion: "Cosecha y apilado de heno; mantenimiento de cercas, edificios y terrenos agrícolas; posibles trabajos en fines de semana o feriados.",
    salario: "$16.83 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25155-052367",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Rob and Court Farms",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Tillar, Arkansas",
    descripcion: "Operación de maquinaria agrícola para labranza, siembra y cosecha de granos; mantenimiento y reparación de equipos y sistemas de riego.",
    salario: "$14.83 por hora",
    posiciones: ["3"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25169-108279",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Sleepy Creek Farms",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Forsyth, Georgia",
    descripcion: "Cuidado de ganado, incluyendo alimentación, medicación y manejo; mantenimiento de cercas y equipos; corte y empacado de heno.",
    salario: "$16.08 por hora",
    posiciones: ["3"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25156-056454",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Dickens Family Farm LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Leakesville, Misisipi",
    descripcion: "Operación de maquinaria agrícola para corte y almacenamiento de heno; cuidado de ganado; mantenimiento de equipos y estructuras agrícolas.",
    salario: "$14.83 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25170-113604",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "B & B Brost Farms",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Earl Park, Indiana",
    descripcion: "Recepción y almacenamiento de granos; operación de maquinaria agrícola y equipos de almacenamiento; mantenimiento de equipos y áreas de trabajo.",
    salario: "$19.57 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25168-103247",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Walther Farms LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Boardman, Oregón",
    descripcion: "Operación de maquinaria agrícola con GPS para cultivo y cosecha de papas; mantenimiento de equipos y tareas de irrigación.",
    salario: "$19.82 por hora",
    posiciones: ["3"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25169-106484",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Salinger's Orchards Inc",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Brewster, Nueva York",
    descripcion: "Manejo de tractores y equipos agrícolas para labranza, plantación y cosecha de frutas; transporte de suministros y mantenimiento de equipos.",
    salario: "$18.83 por hora",
    posiciones: ["3"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25174-120396",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Tyler and Lisa Lane Joint Venture",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Plainview, Texas",
    descripcion: "Operación de maquinaria agrícola para cultivo de maíz, trigo, sorgo y algodón; mantenimiento de sistemas de riego y equipos.",
    salario: "$15.79 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25051-711880",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Sugar Square Farms",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Hereford, Texas",
    descripcion: "Manejo de equipos agrícolas para siembra y cosecha de maíz, trigo y sorgo; mantenimiento de maquinaria y transporte de granos.",
    salario: "$15.79 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25162-079894",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Greene's Farms, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Bunnell, Florida",
    descripcion: "Operación de tractores y equipos agrícolas para plantación y cosecha; aplicación de pesticidas y mantenimiento de instalaciones.",
    salario: "$16.28 por hora",
    posiciones: ["8"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25150-036182",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Siddens Farms",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Albany, Misuri",
    descripcion: "Preparación de campos y operación de maquinaria para cultivo de granos; transporte de insumos y mantenimiento de equipos.",
    salario: "$18.65 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25162-078973",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Jarriel Farm Girls, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Collins, Georgia",
    descripcion: "Operación de tractores y maquinaria para cultivo y cosecha de cacahuetes y pacanas; mantenimiento de equipos y estructuras agrícolas.",
    salario: "$14.68 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24229-273233",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Brett Ortmeier",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Dodge, Nebraska",
    descripcion: "Manejo de maquinaria agrícola para cosecha de maíz y soya; mantenimiento de equipos y transporte de cultivos.",
    salario: "$19.21 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25169-105995",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Donato Farms Inc",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Modena, Nueva York",
    descripcion: "Operación de tractores y maquinaria para cultivo y cosecha de frutas y verduras; transporte de trabajadores y mantenimiento de equipos.",
    salario: "$18.83 por hora",
    posiciones: ["15"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25160-068456",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "MattMelon Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Seaford, Delaware",
    descripcion: "Operación de equipos agrícolas para cultivo y cosecha de maíz, soya y sandía; mantenimiento de sistemas de riego y equipos.",
    salario: "$17.96 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25097-839271",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Migo Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Elizabeth City, Carolina del Norte",
    descripcion: "Cosecha de vegetales, mantenimiento de campos, incluyendo atado, poda y limpieza de sistemas de riego.",
    salario: "$14.91 por hora",
    posiciones: ["30"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25150-033867",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "RJ Harvesting, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Frostproof, Florida",
    descripcion: "Cosecha manual de cítricos utilizando sacos de recolección y escaleras; mantenimiento general del huerto.",
    salario: "$14.77 por hora",
    posiciones: ["15"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24338-513363",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Farm-Op Kuzzens H2A, LLC (FT22)",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Labelle, Florida",
    descripcion: "Instalación de plástico y sistemas de riego, plantación y mantenimiento de cultivos, incluyendo reparación de plásticos y sistemas de riego.",
    salario: "$12.41 por hora",
    posiciones: ["265"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-22341-627008",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Nunez Pine Straw, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Baxley, Georgia",
    descripcion: "Trabajo en invernadero, incluyendo plantación, riego, trasplante y etiquetado de plantas; mantenimiento general de la finca.",
    salario: "$14.77 por hora",
    posiciones: ["30"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24304-442071",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Fresh Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Oxnard, California",
    descripcion: "Cosecha de bayas (fresa, arándano, zarzamora) tanto manual como con máquina; mantenimiento general de la finca y preparación de cultivos para envío.",
    salario: "$19.97 por hora",
    posiciones: ["120"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24352-551818",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "JVKS Harvest Solutions, LLC dba AgSocio",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Gonzales, California",
    descripcion: "Cosecha de lechuga, repollo y apio; empaque manual en el campo y operación de maquinaria agrícola.",
    salario: "$19.97 por hora",
    posiciones: ["240"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25028-646192",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "FMG Farm Contractor Inc",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Salinas, California",
    descripcion: "Cosecha de fresas, mantenimiento de cultivos y operación de maquinaria agrícola; se requiere experiencia previa.",
    salario: "$19.97 por hora",
    posiciones: ["27"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25073-778118",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Rodriguez Bros. Ranch, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Gilroy, California",
    descripcion: "Cosecha de bayas y vegetales mixtos; mantenimiento de cultivos y preparación de productos para el mercado.",
    salario: "$19.97 por hora",
    posiciones: ["35"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24351-548043",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Fresh Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "King City, California",
    descripcion: "Cosecha y trasplante de plantas, operación de maquinaria agrícola y mantenimiento de invernaderos y viveros.",
    salario: "$19.97 por hora",
    posiciones: ["87"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25006-597594",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Fresh Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "McFarland, California",
    descripcion: "Cosecha manual de uvas de mesa, empaque en el campo y mantenimiento general de la finca.",
    salario: "$19.97 por hora",
    posiciones: ["128"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25134-977968",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Fresh Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Bakersfield, California",
    descripcion: "Cosecha de vegetales, deshierbe, trasplante y operación de maquinaria agrícola; se requiere experiencia previa.",
    salario: "$19.97 por hora",
    posiciones: ["65"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24365-576835",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Fresh Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Salinas, California",
    descripcion: "Cosecha de bayas, mantenimiento de cultivos y operación de maquinaria agrícola; se requiere experiencia previa.",
    salario: "$19.97 por hora",
    posiciones: ["64"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25062-739917",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Fresh Harvest, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Buckeye, Arizona",
    descripcion: "Cosecha de cebollas, remolachas y nabos; clasificación y empaque en el campo; se requiere experiencia previa.",
    salario: "$17.04 por hora",
    posiciones: ["50"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24334-507521",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Foothill Packing, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "San Luis, Arizona",
    descripcion: "Deshierbe manual, adelgazamiento de cultivos y limpieza de campos; se requiere experiencia previa.",
    salario: "$16.32 por hora",
    posiciones: ["263"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-24207-223672",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Amazing Cleaning, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Branson, Missouri",
    descripcion: "Limpieza profunda de edificios y terrenos, incluyendo pisos, alfombras, paredes y ventanas; retiro de basura y mantenimiento general.",
    salario: "$15.12 por hora",
    posiciones: ["30"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-25001-580116",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Titania Crew LTD",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Big Sky, Montana",
    descripcion: "Limpieza intensiva de interiores y exteriores, incluyendo baños, cocinas y áreas públicas; manejo de residuos y mantenimiento de equipos.",
    salario: "$16.53 por hora",
    posiciones: ["23"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-24002-602659",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Mackinac Island Carriage Tours, Inc.",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Mackinac Island, Michigan",
    descripcion: "Limpieza nocturna de instalaciones, incluyendo pisos, paredes y eliminación de basura; mantenimiento rutinario y reportes de reparaciones necesarias.",
    salario: "$16.19 por hora",
    posiciones: ["8"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-25001-584947",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Empire Farm Labor Contractor LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Salinas, California",
    descripcion: "Supervisión de limpieza de baños portátiles y cumplimiento de protocolos de higiene en campos agrícolas; apoyo en actividades de cosecha cuando sea necesario.",
    salario: "$20.13 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-300-25033-659621",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Hugo's Pool Service Inc",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Barnegat, Nueva Jersey",
    descripcion: "Servicios de limpieza y mantenimiento de piscinas, incluyendo apertura, cierre y cuidado durante el invierno; manejo de productos químicos y equipos especializados.",
    salario: "$21.29 por hora",
    posiciones: ["4"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-25001-581602",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "The Country Club of Little Rock",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Little Rock, Arkansas",
    descripcion: "Limpieza y mantenimiento de instalaciones del club, incluyendo pisos, alfombras, ventanas y mobiliario; preparación de áreas para eventos.",
    salario: "$13.43 por hora",
    posiciones: ["3"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-23353-579145",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Thundering Surf (LBI Recreation Center, Inc.)",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Beach Haven, Nueva Jersey",
    descripcion: "Limpieza intensiva de áreas interiores y exteriores, incluyendo baños, cocinas y áreas públicas; manejo de residuos y mantenimiento de equipos.",
    salario: "$19.22 por hora",
    posiciones: ["1"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-23001-670692",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Nantucket Island Resorts / White Elephant Resorts",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Nantucket, Massachusetts",
    descripcion: "Limpieza de habitaciones y áreas comunes en resorts, incluyendo pisos, alfombras, ventanas y mobiliario; cumplimiento de protocolos de higiene y seguridad.",
    salario: "$19.10 por hora",
    posiciones: ["13"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-23001-673061",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Tidewater Inn (Hari Hospitality, Inc.)",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "West Yarmouth, Massachusetts",
    descripcion: "Limpieza y mantenimiento de habitaciones y áreas comunes del hotel, incluyendo pisos, alfombras, ventanas y mobiliario; cumplimiento de protocolos de higiene.",
    salario: "$19.20 por hora",
    posiciones: ["2"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-21001-989502",
    boton: "Ver vacante",
    cerrado: false
  },
  {
    logo: "/iconofarmworker.png",
    empresa: "Extreme Getaway Homes, LLC",
    estado: "Abierto",
    estadoColor: "bg-green-400",
    ubicacion: "Reunion, Florida",
    descripcion: "Limpieza profunda de propiedades vacacionales, incluyendo pisos, alfombras, paredes y ventanas; retiro de basura y mantenimiento general.",
    salario: "$11.77 por hora",
    posiciones: ["15"],
    idioma: "Inglés",
    link: "https://seasonaljobs.dol.gov/jobs/H-400-21001-990491",
    boton: "Ver vacante",
    cerrado: false
  }
];

export default vacantes;



